# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Currency_pb2 as Currency__pb2


class CurrencyRatesStreamStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCurrencyRates = channel.unary_stream(
        '/CurrencyRatesStream/GetCurrencyRates',
        request_serializer=Currency__pb2.RatesRequest.SerializeToString,
        response_deserializer=Currency__pb2.RatesRespond.FromString,
        )


class CurrencyRatesStreamServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCurrencyRates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyRatesStreamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCurrencyRates': grpc.unary_stream_rpc_method_handler(
          servicer.GetCurrencyRates,
          request_deserializer=Currency__pb2.RatesRequest.FromString,
          response_serializer=Currency__pb2.RatesRespond.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CurrencyRatesStream', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
